### ISSUE TITLE
Implement IUniswapV2Callee interface?

### ISSUE THREAD

**Issue by 524119574** [Austin-Williams/uniswap-flash-swapper#10]
Hi according to the example [here](https://github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/examples/ExampleFlashSwap.sol) it seems like we need to implement the `IUniswapV2Callee `, but this doesn't seem to be implemented in the `UniswapFlashSwapper`. Any idea why is this the case?

**Comment by Austin-Williams** [comment]
Ah, so. We actually _do_ implement that interface. Just not explicitly.

The [`IUniswapV2Callee` interface](https://github.com/Uniswap/uniswap-v2-core/blob/master/contracts/interfaces/IUniswapV2Callee.sol) just requires [a `uniswapV2Call` funciton](https://github.com/Uniswap/uniswap-v2-core/blob/master/contracts/interfaces/IUniswapV2Callee.sol#L4).

And we implement that function [here](https://github.com/Austin-Williams/uniswap-flash-swapper/blob/master/contracts/UniswapFlashSwapper.sol#L66) in the `UniswapFlashSwapper` contract that we inherit in our [`ExampleContract`](https://github.com/Austin-Williams/uniswap-flash-swapper/blob/master/contracts/Example.sol#L5).
